"$schema" = "../../node_modules/wrangler/config-schema.json"
name = "arcaea-packs-inventory"
main = "src/index.ts"
compatibility_date = "2025-11-28"

[observability]
enabled = true

[[routes]]
custom_domain = true
pattern = "arcinv.sevenc7c.com"

[version_metadata]
binding = "VERSION_METADATA"

[assets]
directory = "../web/dist"
binding = "ASSETS"
run_worker_first = ["/"]
